[package]
name = "external"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
tokio.workspace = true
general.workspace = true
axum.workspace = true
