[workspace]
members = ["packages/*"]
resolver = "3"

[workspace.package]
name = "islam-central"
authors = ["Kasra Alizadeh <ksrhdzl@gmail.com>"]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
general = { path = "packages/general" }
