[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
name = "islam-central"
authors = ["Kasra Alizadeh <ksrhdzl@gmail.com>"]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
axum = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
general = { path = "crates/general" }
