name: "Install"
description: "Install and pre-build"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        registry-url: 'https://registry.npmjs.org'

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Get cache directory
      shell: bash
      run: |
        echo "CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/.yarnrc.yml') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn workspaces focus ${{github.workflow}}