name: external

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/external/**"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/external/**"
  workflow_run:
    workflows: [general]
    types:
      - completed
  workflow_dispatch:

jobs:
  audit:
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run audit
        run: yarn workspace ${{github.workflow}} npm audit

  lint:
    needs:
      - audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build Common
        run: yarn workspace common run build

      - name: Run lint
        run: yarn workspace ${{github.workflow}} run lint

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run build
        run: yarn dlx turbo run build --filter=${{github.workflow}}

  deploy:
    needs:
      - build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{github.workflow}}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/${{github.workflow}}/dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
