name: general

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/general/**"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/general/**"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run audit
        run: yarn workspace ${{github.workflow}} npm audit

  lint:
    needs:
      - audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run lint
        run: yarn workspace ${{github.workflow}} run lint

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run build
        run: yarn dlx turbo run build --filter=${{github.workflow}}
